# Generate .env file for Kubernetes deployment (PowerShell)
# This script creates a .env file with secure random values
#
# Usage:
#   .\generate-env.ps1
#   .\generate-env.ps1 -Force   # Overwrite existing .env file

param(
    [switch]$Force  # Overwrite existing .env file
)

$ErrorActionPreference = "Stop"

# Colors for output
$ColorInfo = "Green"
$ColorWarn = "Yellow"
$ColorError = "Red"

function Write-InfoLog {
    param([string]$Message)
    Write-Host "[INFO] $Message" -ForegroundColor $ColorInfo
}

function Write-WarnLog {
    param([string]$Message)
    Write-Host "[WARN] $Message" -ForegroundColor $ColorWarn
}

function Write-ErrorLog {
    param([string]$Message)
    Write-Host "[ERROR] $Message" -ForegroundColor $ColorError
}

$EnvFile = ".env"

# Check if .env already exists
if ((Test-Path $EnvFile) -and -not $Force) {
    Write-WarnLog ".env file already exists at: $EnvFile"
    Write-WarnLog "Use .\scripts\generate-env.ps1 -Force to overwrite"
    exit 0
}

Write-InfoLog "Generating secure environment variables..."

# Generate secure random passwords
function Generate-SecurePassword {
    param([int]$Length = 16)
    $chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789!@#$%^&*"
    $password = ""
    for ($i = 0; $i -lt $Length; $i++) {
        $password += $chars[(Get-Random -Maximum $chars.Length)]
    }
    return $password
}

# Generate fernet key
$FernetKey = ""
try {
    $FernetKey = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>$null
    if (-not $FernetKey) {
        throw "Python not available"
    }
    Write-InfoLog "Generated fernet key using Python"
} catch {
    Write-WarnLog "Python not available for fernet key generation, using fallback method"
    # Fallback: generate a random base64 string
    $randomBytes = New-Object byte[] 32
    [System.Security.Cryptography.RandomNumberGenerator]::Create().GetBytes($randomBytes)
    $FernetKey = [Convert]::ToBase64String($randomBytes)
}

# Generate secure passwords
$MongoPassword = Generate-SecurePassword
$PostgresPassword = Generate-SecurePassword
$AirflowWebserverKey = Generate-SecurePassword
$AirflowPassword = Generate-SecurePassword

# Create .env file content
$EnvContent = @"
# Kubernetes Environment Configuration
# Auto-generated by generate-env.ps1
# Created: $(Get-Date)
#
# IMPORTANT SECURITY NOTES:
# - DO NOT commit this file to version control!
# - Change these values for production deployment
# - Store securely and backup in a password manager
#
# To regenerate: .\scripts\generate-env.ps1 -Force

# MongoDB Credentials
MONGODB_ADMIN_USER=admin
MONGODB_ADMIN_PASSWORD=$MongoPassword

# PostgreSQL Credentials
POSTGRES_ADMIN_USER=postgres
POSTGRES_ADMIN_PASSWORD=$PostgresPassword
POSTGRES_AIRFLOW_USER=airflow
POSTGRES_AIRFLOW_PASSWORD=airflow

# Airflow Credentials
AIRFLOW_FERNET_KEY=$FernetKey
AIRFLOW_WEBSERVER_SECRET_KEY=$AirflowWebserverKey
AIRFLOW_ADMIN_USER=admin
AIRFLOW_ADMIN_PASSWORD=$AirflowPassword
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8

Write-InfoLog ".env file created successfully!"
Write-InfoLog "Location: $EnvFile"
Write-Host ""
Write-Host "Generated credentials summary:" -ForegroundColor Cyan
Write-Host "  MongoDB Admin: admin / ******* (hidden)" -ForegroundColor White
Write-Host "  PostgreSQL Admin: postgres / ******* (hidden)" -ForegroundColor White
Write-Host "  Airflow Admin: admin / ******* (hidden)" -ForegroundColor White
Write-Host "  Fernet Key: Generated and secure" -ForegroundColor White
Write-Host ""
Write-Host "Security recommendations:" -ForegroundColor Yellow
Write-Host "  1. Store this .env file securely (not in version control)" -ForegroundColor White
Write-Host "  2. Use a password manager to backup these credentials" -ForegroundColor White
Write-Host "  3. Change passwords before production deployment" -ForegroundColor White
Write-Host "  4. Consider using Kubernetes secrets management (e.g., Sealed Secrets)" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review the generated .env file" -ForegroundColor White
Write-Host "  2. Run deployment: .\scripts\deploy.ps1" -ForegroundColor White