#!/bin/bash
# Generate .env file for Kubernetes deployment (Bash)
# This script creates a .env file with secure random values
#
# Usage:
#   ./generate-env.sh
#   ./generate-env.sh --force   # Overwrite existing .env file

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# Parse arguments
FORCE=false
if [ "$1" = "--force" ]; then
    FORCE=true
fi

ENV_FILE=".env"

# Check if .env already exists
if [ -f "$ENV_FILE" ] && [ "$FORCE" != "true" ]; then
    log_warn ".env file already exists at: $ENV_FILE"
    log_warn "Use ./scripts/generate-env.sh --force to overwrite"
    exit 0
fi

log_info "Generating secure environment variables..."

# Generate secure random passwords
generate_password() {
    local length=${1:-16}
    # Use /dev/urandom for secure random generation
    if command -v openssl &> /dev/null; then
        openssl rand -base64 $length | tr -d "=+/" | cut -c1-$length
    else
        # Fallback to /dev/urandom
        tr -dc 'a-zA-Z0-9!@#$%^&*' < /dev/urandom | head -c $length
    fi
}

# Generate fernet key
FERNET_KEY=""
if command -v python3 &> /dev/null; then
    FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    log_info "Generated fernet key using python3"
elif command -v python &> /dev/null; then
    FERNET_KEY=$(python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())")
    log_info "Generated fernet key using python"
else
    log_warn "Python not available for fernet key generation, using fallback method"
    # Fallback: generate a random base64 string
    FERNET_KEY=$(openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64)
fi

# Generate secure passwords
MONGO_PASSWORD=$(generate_password 16)
POSTGRES_PASSWORD=$(generate_password 16)
AIRFLOW_WEBSERVER_KEY=$(generate_password 24)
AIRFLOW_PASSWORD=$(generate_password 12)

# Create .env file content
cat > "$ENV_FILE" << EOF
# Kubernetes Environment Configuration
# Auto-generated by generate-env.sh
# Created: $(date)
#
# IMPORTANT SECURITY NOTES:
# - DO NOT commit this file to version control!
# - Change these values for production deployment
# - Store securely and backup in a password manager
#
# To regenerate: ./scripts/generate-env.sh --force

# MongoDB Credentials
MONGODB_ADMIN_USER=admin
MONGODB_ADMIN_PASSWORD=$MONGO_PASSWORD

# PostgreSQL Credentials
POSTGRES_ADMIN_USER=postgres
POSTGRES_ADMIN_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_AIRFLOW_USER=airflow
POSTGRES_AIRFLOW_PASSWORD=airflow

# Airflow Credentials
AIRFLOW_FERNET_KEY=$FERNET_KEY
AIRFLOW_WEBSERVER_SECRET_KEY=$AIRFLOW_WEBSERVER_KEY
AIRFLOW_ADMIN_USER=admin
AIRFLOW_ADMIN_PASSWORD=$AIRFLOW_PASSWORD
EOF

log_info ".env file created successfully!"
log_info "Location: $ENV_FILE"
echo ""
echo -e "${GREEN}Generated credentials summary:${NC}"
echo "  MongoDB Admin: admin / ******* (hidden)"
echo "  PostgreSQL Admin: postgres / ******* (hidden)"
echo "  Airflow Admin: admin / ******* (hidden)"
echo "  Fernet Key: Generated and secure"
echo ""
echo -e "${YELLOW}Security recommendations:${NC}"
echo "  1. Store this .env file securely (not in version control)"
echo "  2. Use a password manager to backup these credentials"
echo "  3. Change passwords before production deployment"
echo "  4. Consider using Kubernetes secrets management (e.g., Sealed Secrets)"
echo ""
echo -e "${GREEN}Next steps:${NC}"
echo "  1. Review the generated .env file"
echo "  2. Run deployment: ./scripts/deploy.sh"