#!/bin/bash
# PostgreSQL Environment Setup Script (Bash)
#
# This script creates a .env file for PostgreSQL Docker setup
# It sets up admin credentials and application-specific database configurations
#
# IMPORTANT: This script should be run from the postgres/ folder
# It will create the .env file in the postgres_config/ subfolder
#
# Usage:
#   ./scripts/setup-env.sh
#   ./scripts/setup-env.sh --force    # Overwrite existing .env file

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
CONFIG_DIR="$PARENT_DIR/postgres_config"
ENV_FILE="$CONFIG_DIR/.env"

echo "PostgreSQL Environment Setup Script"
echo "===================================="
echo ""

# Parse arguments
FORCE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --force)
            FORCE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Check if .env already exists
if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != true ]]; then
    echo ".env file already exists at: $ENV_FILE"
    echo "Use ./scripts/setup-env.sh --force to overwrite"
    exit 0
fi

# Get values from environment variables or use defaults
echo "Checking system environment variables..."

# PostgreSQL Admin User (superuser)
POSTGRES_USER="${POSTGRES_USER:-postgres}"
if [[ "$POSTGRES_USER" == "postgres" ]] && [[ -z "${!POSTGRES_USER}" ]]; then
    echo "  POSTGRES_USER not found, using default: $POSTGRES_USER"
else
    echo "  POSTGRES_USER found: $POSTGRES_USER"
fi

# PostgreSQL Admin Password
POSTGRES_PASSWORD="${POSTGRES_PASSWORD:-postgres}"
if [[ "$POSTGRES_PASSWORD" == "postgres" ]] && [[ -z "${!POSTGRES_PASSWORD}" ]]; then
    echo "  POSTGRES_PASSWORD not found, using default: $POSTGRES_PASSWORD"
    echo "  WARNING: Change this in production!"
else
    echo "  POSTGRES_PASSWORD found"
fi

# Airflow Database Credentials
AIRFLOW_DB_USER="${AIRFLOW_DB_USER:-airflow}"
if [[ "$AIRFLOW_DB_USER" == "airflow" ]] && [[ -z "${!AIRFLOW_DB_USER}" ]]; then
    echo "  AIRFLOW_DB_USER not found, using default: $AIRFLOW_DB_USER"
else
    echo "  AIRFLOW_DB_USER found: $AIRFLOW_DB_USER"
fi

AIRFLOW_DB_PASSWORD="${AIRFLOW_DB_PASSWORD:-airflow}"
if [[ "$AIRFLOW_DB_PASSWORD" == "airflow" ]] && [[ -z "${!AIRFLOW_DB_PASSWORD}" ]]; then
    echo "  AIRFLOW_DB_PASSWORD not found, using default: $AIRFLOW_DB_PASSWORD"
    echo "  WARNING: Change this in production!"
else
    echo "  AIRFLOW_DB_PASSWORD found"
fi

AIRFLOW_DB_NAME="${AIRFLOW_DB_NAME:-airflow}"
if [[ "$AIRFLOW_DB_NAME" == "airflow" ]] && [[ -z "${!AIRFLOW_DB_NAME}" ]]; then
    echo "  AIRFLOW_DB_NAME not found, using default: $AIRFLOW_DB_NAME"
else
    echo "  AIRFLOW_DB_NAME found: $AIRFLOW_DB_NAME"
fi

echo ""
echo "Creating .env file..."

# Create .env file content
cat > "$ENV_FILE" << EOF
# PostgreSQL Configuration
# Auto-generated by setup-env.sh
# Created: $(date)
#
# DO NOT commit this file to version control!

# PostgreSQL Admin (Root) Credentials
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_INITDB_ARGS=

# Port Configuration
POSTGRES_PORT=5432

# Application-Specific Credentials
# Airflow Database
AIRFLOW_DB_USER=$AIRFLOW_DB_USER
AIRFLOW_DB_PASSWORD=$AIRFLOW_DB_PASSWORD
AIRFLOW_DB_NAME=$AIRFLOW_DB_NAME

# Backup and Maintenance
POSTGRES_BACKUP_RETENTION_DAYS=7
POSTGRES_LOG_RETENTION_DAYS=7
EOF

echo ".env file created successfully!"
echo "Location: $ENV_FILE"
echo ""
echo "Summary:"
echo "  PostgreSQL Admin User: $POSTGRES_USER"
echo "  PostgreSQL Admin Password: ******* (hidden)"
echo "  Airflow DB User: $AIRFLOW_DB_USER"
echo "  Airflow DB Name: $AIRFLOW_DB_NAME"
echo ""
echo "Next steps:"
echo "  1. Edit .env file if needed: cat ../postgres_config/.env"
echo "  2. Update airflow/.env with Airflow-specific settings"
echo "  3. Start PostgreSQL container from docker/ folder: docker-compose up -d postgres"
echo "  4. Verify connection: docker-compose exec postgres psql -U $POSTGRES_USER -d postgres -c 'SELECT version();'"
