# PostgreSQL Environment Setup Script (PowerShell)
#
# This script creates a .env file for PostgreSQL Docker setup
# It sets up admin credentials and application-specific database configurations
#
# IMPORTANT: This script should be run from the postgres/ folder
# It will create the .env file in the postgres_config/ subfolder
#
# Usage:
#   .\scripts\setup-env.ps1
#   .\scripts\setup-env.ps1 -Force   # Overwrite existing .env file
#
# To allow script execution:
#   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

param(
    [switch]$Force  # Overwrite existing .env file
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir
$ConfigDir = Join-Path $ParentDir "postgres_config"
$EnvFile = Join-Path $ConfigDir ".env"

Write-Host "PostgreSQL Environment Setup Script" -ForegroundColor Cyan
Write-Host "====================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Host ".env file already exists at: $EnvFile" -ForegroundColor Yellow
    Write-Host "Use .\scripts\setup-env.ps1 -Force to overwrite" -ForegroundColor Yellow
    exit 0
}

# Get values from environment variables or use defaults
Write-Host "Checking system environment variables..." -ForegroundColor Cyan

# PostgreSQL Admin User (superuser)
$POSTGRES_USER = $env:POSTGRES_USER
if (-not $POSTGRES_USER) {
    $POSTGRES_USER = "postgres"
    Write-Host "  POSTGRES_USER not found, using default: $POSTGRES_USER" -ForegroundColor Gray
} else {
    Write-Host "  POSTGRES_USER found: $POSTGRES_USER" -ForegroundColor Green
}

$POSTGRES_PASSWORD = $env:POSTGRES_PASSWORD
if (-not $POSTGRES_PASSWORD) {
    $POSTGRES_PASSWORD = "postgres"
    Write-Host "  POSTGRES_PASSWORD not found, using default: $POSTGRES_PASSWORD" -ForegroundColor Gray
    Write-Host "  WARNING: Change this in production!" -ForegroundColor Yellow
} else {
    Write-Host "  POSTGRES_PASSWORD found" -ForegroundColor Green
}

# Airflow Database Credentials
$AIRFLOW_DB_USER = $env:AIRFLOW_DB_USER
if (-not $AIRFLOW_DB_USER) {
    $AIRFLOW_DB_USER = "airflow"
    Write-Host "  AIRFLOW_DB_USER not found, using default: $AIRFLOW_DB_USER" -ForegroundColor Gray
} else {
    Write-Host "  AIRFLOW_DB_USER found: $AIRFLOW_DB_USER" -ForegroundColor Green
}

$AIRFLOW_DB_PASSWORD = $env:AIRFLOW_DB_PASSWORD
if (-not $AIRFLOW_DB_PASSWORD) {
    $AIRFLOW_DB_PASSWORD = "airflow"
    Write-Host "  AIRFLOW_DB_PASSWORD not found, using default: $AIRFLOW_DB_PASSWORD" -ForegroundColor Gray
    Write-Host "  WARNING: Change this in production!" -ForegroundColor Yellow
} else {
    Write-Host "  AIRFLOW_DB_PASSWORD found" -ForegroundColor Green
}

$AIRFLOW_DB_NAME = $env:AIRFLOW_DB_NAME
if (-not $AIRFLOW_DB_NAME) {
    $AIRFLOW_DB_NAME = "airflow"
    Write-Host "  AIRFLOW_DB_NAME not found, using default: $AIRFLOW_DB_NAME" -ForegroundColor Gray
} else {
    Write-Host "  AIRFLOW_DB_NAME found: $AIRFLOW_DB_NAME" -ForegroundColor Green
}

Write-Host ""
Write-Host "Creating .env file..." -ForegroundColor Cyan

# Create .env file content
$EnvContent = @"
# PostgreSQL Configuration
# Auto-generated by setup-env.ps1
# Created: $(Get-Date)
#
# DO NOT commit this file to version control!

# PostgreSQL Admin (Root) Credentials
POSTGRES_USER=$POSTGRES_USER
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_INITDB_ARGS=

# Port Configuration
POSTGRES_PORT=5432

# Application-Specific Credentials
# Airflow Database
AIRFLOW_DB_USER=$AIRFLOW_DB_USER
AIRFLOW_DB_PASSWORD=$AIRFLOW_DB_PASSWORD
AIRFLOW_DB_NAME=$AIRFLOW_DB_NAME

# Backup and Maintenance
POSTGRES_BACKUP_RETENTION_DAYS=7
POSTGRES_LOG_RETENTION_DAYS=7
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8

Write-Host ".env file created successfully!" -ForegroundColor Green
Write-Host "Location: $EnvFile" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  PostgreSQL Admin User: $POSTGRES_USER" -ForegroundColor White
Write-Host "  PostgreSQL Admin Password: ******* (hidden)" -ForegroundColor White
Write-Host "  Airflow DB User: $AIRFLOW_DB_USER" -ForegroundColor White
Write-Host "  Airflow DB Name: $AIRFLOW_DB_NAME" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Edit .env file if needed: Get-Content .\postgres_config\.env" -ForegroundColor White
Write-Host "  2. Update airflow/.env with Airflow-specific settings" -ForegroundColor White
Write-Host "  3. Start PostgreSQL container from docker/ folder: docker-compose up -d postgres" -ForegroundColor White
Write-Host "  4. Verify connection: docker-compose exec postgres psql -U $POSTGRES_USER -d postgres -c 'SELECT version();'" -ForegroundColor White
