#!/bin/bash
# Apache Airflow Environment Setup Script (Bash)
#
# This script creates a .env file for Apache Airflow Docker setup
# It sets up Airflow-specific configuration
#
# IMPORTANT: Database credentials are managed via postgres/postgres_config/.env
# This script should be run from the airflow/ folder
# It will create the .env file in the airflow_config/ subfolder
#
# Usage:
#   ./scripts/setup-env.sh
#   ./scripts/setup-env.sh --force    # Overwrite existing .env file

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
CONFIG_DIR="$PARENT_DIR/airflow_config"
ENV_FILE="$CONFIG_DIR/.env"

echo "Apache Airflow Environment Setup Script"
echo "========================================"
echo ""

# Parse arguments
FORCE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --force)
            FORCE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Check if .env already exists
if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != true ]]; then
    echo ".env file already exists at: $ENV_FILE"
    echo "Use ./scripts/setup-env.sh --force to overwrite"
    exit 0
fi

# Generate Fernet Key
echo "Generating Fernet key for data encryption..."
FERNET_KEY=$(python3 -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>/dev/null)
if [ $? -ne 0 ]; then
    FERNET_KEY="FERNET_KEY_PLACEHOLDER_CHANGE_THIS"
    echo "  Python cryptography not found. Using placeholder."
    echo "  Install with: pip install cryptography"
else
    echo "  Fernet key generated successfully"
fi

# Get values from environment variables or use defaults
echo "Checking system environment variables..."

# AIRFLOW_EXECUTOR
AIRFLOW_EXECUTOR="${AIRFLOW_EXECUTOR:-LocalExecutor}"
if [[ "$AIRFLOW_EXECUTOR" == "LocalExecutor" ]] && [[ -z "${!AIRFLOW_EXECUTOR}" ]]; then
    echo "  AIRFLOW_EXECUTOR not found, using default: $AIRFLOW_EXECUTOR"
else
    echo "  AIRFLOW_EXECUTOR found: $AIRFLOW_EXECUTOR"
fi

# AIRFLOW_WEBSERVER_PORT
AIRFLOW_WEBSERVER_PORT="${AIRFLOW_WEBSERVER_PORT:-8080}"
if [[ "$AIRFLOW_WEBSERVER_PORT" == "8080" ]] && [[ -z "${!AIRFLOW_WEBSERVER_PORT}" ]]; then
    echo "  AIRFLOW_WEBSERVER_PORT not found, using default: $AIRFLOW_WEBSERVER_PORT"
else
    echo "  AIRFLOW_WEBSERVER_PORT found: $AIRFLOW_WEBSERVER_PORT"
fi

# Generate random secret key
SECRET_KEY=$(openssl rand -hex 32)

echo ""
echo "Creating .env file..."

# Create .env file content
cat > "$ENV_FILE" << EOF
# Apache Airflow Environment Configuration
# Auto-generated by setup-env.sh
# Created: $(date)
#
# DO NOT commit this file to version control!
# Database credentials are loaded from ../postgres/postgres_config/.env

# Airflow Core Settings
AIRFLOW_HOME=/home/airflow
AIRFLOW__CORE__DAGS_FOLDER=/home/airflow/dags
AIRFLOW__CORE__LOGS_FOLDER=/home/airflow/logs
AIRFLOW__CORE__PLUGIN_FOLDER=/home/airflow/plugins

# Executor Configuration
AIRFLOW__CORE__EXECUTOR=$AIRFLOW_EXECUTOR

# Fernet Key (for encrypting sensitive data)
AIRFLOW__CORE__FERNET_KEY=$FERNET_KEY

# Airflow Web UI Settings
AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
AIRFLOW__WEBSERVER__EXPOSE_CONFIG=False
AIRFLOW__WEBSERVER__SECRET_KEY=$SECRET_KEY

# Service Ports
AIRFLOW_WEBSERVER_PORT=$AIRFLOW_WEBSERVER_PORT
EOF

echo ".env file created successfully!"
echo "Location: $ENV_FILE"
echo ""
echo "Summary:"
echo "  AIRFLOW_EXECUTOR: $AIRFLOW_EXECUTOR"
echo "  AIRFLOW_WEBSERVER_PORT: $AIRFLOW_WEBSERVER_PORT"
echo "  AIRFLOW__CORE__FERNET_KEY: $(if [[ "$FERNET_KEY" == "FERNET_KEY_PLACEHOLDER_CHANGE_THIS" ]]; then echo 'PLACEHOLDER (needs update)'; else echo '✓ Generated'; fi)"
echo ""

if [[ "$FERNET_KEY" == "FERNET_KEY_PLACEHOLDER_CHANGE_THIS" ]]; then
    echo "⚠️  ACTION REQUIRED:"
    echo "Install cryptography package and regenerate Fernet key:"
    echo "  pip install cryptography"
    echo "  python3 -c \"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())\""
    echo "Then update AIRFLOW__CORE__FERNET_KEY in .env"
    echo ""
fi

echo "Next steps:"
echo "  1. Set up PostgreSQL first:"
echo "     - Run postgres setup script from postgres/ folder"
echo "     - Start PostgreSQL: docker-compose up -d postgres"
echo "  2. Edit .env file if needed: cat ../airflow_config/.env"
echo "  3. Create Airflow database and user on PostgreSQL:"
echo "     - docker-compose exec postgres psql -U postgres -c \"CREATE USER airflow WITH ENCRYPTED PASSWORD 'airflow'; CREATE DATABASE airflow OWNER airflow; GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;\""
echo "  4. Start Airflow services from docker/ folder: docker-compose up -d airflow-webserver airflow-scheduler"
echo "  5. Initialize Airflow database: docker-compose exec airflow-webserver airflow db migrate"
echo "  6. Create admin user: docker-compose exec airflow-webserver airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com"
echo "  7. Access web UI: http://localhost:8080"
