# Apache Airflow Environment Setup Script (PowerShell)
#
# This script creates a .env file for Apache Airflow Docker setup
# It checks for system environment variables and uses sensible defaults
#
# IMPORTANT: This script should be run from the airflow/ folder
# It will create the .env file in the airflow_config/ subfolder
#
# Usage:
#   .\scripts\setup-env.ps1
#   .\scripts\setup-env.ps1 -Force   # Overwrite existing .env file
#
# To allow script execution:
#   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

param(
    [switch]$Force  # Overwrite existing .env file
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir
$ConfigDir = Join-Path $ParentDir "airflow_config"
$EnvFile = Join-Path $ConfigDir ".env"

Write-Host "Apache Airflow Environment Setup Script" -ForegroundColor Cyan
Write-Host "========================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Host ".env file already exists at: $EnvFile" -ForegroundColor Yellow
    Write-Host "Use .\scripts\setup-env.ps1 -Force to overwrite" -ForegroundColor Yellow
    exit 0
}

# Generate Fernet Key
Write-Host "Generating Fernet key for data encryption..." -ForegroundColor Cyan
try {
    # Try using Python if available
    $FernetKey = python -c "from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())" 2>$null
    if ($LASTEXITCODE -ne 0) {
        # Fallback: use a placeholder
        $FernetKey = "FERNET_KEY_PLACEHOLDER_CHANGE_THIS"
        Write-Host "  Python not found. Using placeholder. Run: python -c `"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())`"" -ForegroundColor Yellow
    } else {
        Write-Host "  Fernet key generated successfully" -ForegroundColor Green
    }
} catch {
    $FernetKey = "FERNET_KEY_PLACEHOLDER_CHANGE_THIS"
    Write-Host "  Could not generate Fernet key. Using placeholder." -ForegroundColor Yellow
}

# Get values from environment variables or use defaults
Write-Host "Checking system environment variables..." -ForegroundColor Cyan

$POSTGRES_USER = $env:POSTGRES_USER
if (-not $POSTGRES_USER) {
    $POSTGRES_USER = "airflow"
    Write-Host "  POSTGRES_USER not found, using default: $POSTGRES_USER" -ForegroundColor Gray
} else {
    Write-Host "  POSTGRES_USER found: $POSTGRES_USER" -ForegroundColor Green
}

$POSTGRES_PASSWORD = $env:POSTGRES_PASSWORD
if (-not $POSTGRES_PASSWORD) {
    $POSTGRES_PASSWORD = "airflow"
    Write-Host "  POSTGRES_PASSWORD not found, using default: $POSTGRES_PASSWORD" -ForegroundColor Gray
    Write-Host "  WARNING: Change this in production!" -ForegroundColor Yellow
} else {
    Write-Host "  POSTGRES_PASSWORD found" -ForegroundColor Green
}

$POSTGRES_DB = $env:POSTGRES_DB
if (-not $POSTGRES_DB) {
    $POSTGRES_DB = "airflow"
    Write-Host "  POSTGRES_DB not found, using default: $POSTGRES_DB" -ForegroundColor Gray
} else {
    Write-Host "  POSTGRES_DB found: $POSTGRES_DB" -ForegroundColor Green
}

$AIRFLOW_EXECUTOR = $env:AIRFLOW_EXECUTOR
if (-not $AIRFLOW_EXECUTOR) {
    $AIRFLOW_EXECUTOR = "LocalExecutor"
    Write-Host "  AIRFLOW_EXECUTOR not found, using default: $AIRFLOW_EXECUTOR" -ForegroundColor Gray
} else {
    Write-Host "  AIRFLOW_EXECUTOR found: $AIRFLOW_EXECUTOR" -ForegroundColor Green
}

$AIRFLOW_WEBSERVER_PORT = $env:AIRFLOW_WEBSERVER_PORT
if (-not $AIRFLOW_WEBSERVER_PORT) {
    $AIRFLOW_WEBSERVER_PORT = "8080"
    Write-Host "  AIRFLOW_WEBSERVER_PORT not found, using default: $AIRFLOW_WEBSERVER_PORT" -ForegroundColor Gray
} else {
    Write-Host "  AIRFLOW_WEBSERVER_PORT found: $AIRFLOW_WEBSERVER_PORT" -ForegroundColor Green
}

Write-Host ""
Write-Host "Creating .env file..." -ForegroundColor Cyan

# Create .env file content
$EnvContent = @"
# Apache Airflow Environment Configuration
# Auto-generated by setup-env.ps1
# Created: $(Get-Date)
#
# DO NOT commit this file to version control!
# Database credentials are loaded from ../postgres/postgres_config/.env

# Airflow Core Settings
AIRFLOW_HOME=/home/airflow
AIRFLOW__CORE__DAGS_FOLDER=/home/airflow/dags
AIRFLOW__CORE__LOGS_FOLDER=/home/airflow/logs
AIRFLOW__CORE__PLUGIN_FOLDER=/home/airflow/plugins

# Executor Configuration
AIRFLOW__CORE__EXECUTOR=$AIRFLOW_EXECUTOR

# Fernet Key (for encrypting sensitive data)
AIRFLOW__CORE__FERNET_KEY=$FernetKey

# Airflow Web UI Settings
AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
AIRFLOW__WEBSERVER__EXPOSE_CONFIG=False
AIRFLOW__WEBSERVER__SECRET_KEY=$(New-Guid).ToString().Replace('-','')

# Service Ports
AIRFLOW_WEBSERVER_PORT=$AIRFLOW_WEBSERVER_PORT
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8

Write-Host ".env file created successfully!" -ForegroundColor Green
Write-Host "Location: $EnvFile" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  AIRFLOW_EXECUTOR: $AIRFLOW_EXECUTOR" -ForegroundColor White
Write-Host "  AIRFLOW_WEBSERVER_PORT: $AIRFLOW_WEBSERVER_PORT" -ForegroundColor White
Write-Host "  AIRFLOW__CORE__FERNET_KEY: $(if ($FernetKey -eq 'FERNET_KEY_PLACEHOLDER_CHANGE_THIS') { 'PLACEHOLDER (needs update)' } else { '✓ Generated' })" -ForegroundColor White
Write-Host ""

if ($FernetKey -eq "FERNET_KEY_PLACEHOLDER_CHANGE_THIS") {
    Write-Host "⚠️  ACTION REQUIRED:" -ForegroundColor Yellow
    Write-Host "Install cryptography package and regenerate Fernet key:" -ForegroundColor Yellow
    Write-Host "  pip install cryptography" -ForegroundColor White
    Write-Host "  python -c `"from cryptography.fernet import Fernet; print(Fernet.generate_key().decode())`"" -ForegroundColor White
    Write-Host "Then update AIRFLOW__CORE__FERNET_KEY in .env" -ForegroundColor White
    Write-Host ""
}

Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Set up PostgreSQL first:" -ForegroundColor White
Write-Host "     - Run postgres setup script from postgres/ folder" -ForegroundColor White
Write-Host "     - Start PostgreSQL: docker-compose up -d postgres" -ForegroundColor White
Write-Host "  2. Edit .env file if needed: Get-Content .\airflow_config\.env" -ForegroundColor White
Write-Host "  3. Create Airflow database and user on PostgreSQL:" -ForegroundColor White
Write-Host "     - docker-compose exec postgres psql -U postgres -c `"CREATE USER airflow WITH ENCRYPTED PASSWORD 'airflow'; CREATE DATABASE airflow OWNER airflow; GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;`"" -ForegroundColor White
Write-Host "  4. Start Airflow services from docker/ folder: docker-compose up -d airflow-webserver airflow-scheduler" -ForegroundColor White
Write-Host "  5. Initialize Airflow database: docker-compose exec airflow-webserver airflow db migrate" -ForegroundColor White
Write-Host "  6. Create admin user: docker-compose exec airflow-webserver airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com" -ForegroundColor White
Write-Host "  7. Access web UI: http://localhost:8080" -ForegroundColor White
