# MongoDB Environment Setup Script (PowerShell)
#
# This script creates a .env file for MongoDB Docker setup
# It checks for system environment variables and uses them if available,
# otherwise uses the defaults from .env.example
#
# IMPORTANT: This script should be run from the mongodb/ folder or from scripts/
# It will create the .env file in the mongodb_config/ subfolder
#
# Usage (from mongodb/ folder):
#   .\scripts\setup-env.ps1
#   .\scripts\setup-env.ps1 -Force   # Overwrite existing .env file
#
# To allow script execution, you may need to run:
#   Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

param(
    [switch]$Force  # Overwrite existing .env file
)

$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ParentDir = Split-Path -Parent $ScriptDir
$ConfigDir = Join-Path $ParentDir "mongodb_config"
$EnvFile = Join-Path $ConfigDir ".env"
$EnvExampleFile = Join-Path $ParentDir ".env.example"

Write-Host "MongoDB Environment Setup Script" -ForegroundColor Cyan
Write-Host "=================================" -ForegroundColor Cyan
Write-Host ""

# Check if .env already exists
if ((Test-Path $EnvFile) -and -not $Force) {
    Write-Host ".env file already exists at: $EnvFile" -ForegroundColor Yellow
    Write-Host "Use .\scripts\setup-env.ps1 -Force to overwrite" -ForegroundColor Yellow
    exit 0
}

# Get values from environment variables or use defaults
Write-Host "Checking system environment variables..." -ForegroundColor Cyan

$MONGO_ROOT_USER = $env:MONGO_ROOT_USER
if (-not $MONGO_ROOT_USER) {
    $MONGO_ROOT_USER = $env:MONGODB_USER
}
if (-not $MONGO_ROOT_USER) {
    $MONGO_ROOT_USER = "admin"
    Write-Host "  MONGO_ROOT_USER not found in environment, using default: $MONGO_ROOT_USER" -ForegroundColor Gray
} else {
    Write-Host "  MONGO_ROOT_USER found: $MONGO_ROOT_USER" -ForegroundColor Green
}

$MONGO_ROOT_PASSWORD = $env:MONGO_ROOT_PASSWORD
if (-not $MONGO_ROOT_PASSWORD) {
    $MONGO_ROOT_PASSWORD = $env:MONGODB_PASSWORD
}
if (-not $MONGO_ROOT_PASSWORD) {
    $MONGO_ROOT_PASSWORD = "changeme"
    Write-Host "  MONGO_ROOT_PASSWORD not found in environment, using default: $MONGO_ROOT_PASSWORD" -ForegroundColor Gray
    Write-Host "  WARNING: Using default password! Change this immediately in .env for security" -ForegroundColor Yellow
} else {
    Write-Host "  MONGO_ROOT_PASSWORD found in environment" -ForegroundColor Green
}

$MONGO_DB_NAME = $env:MONGO_DB_NAME
if (-not $MONGO_DB_NAME) {
    $MONGO_DB_NAME = $env:MONGODB_DB_NAME
}
if (-not $MONGO_DB_NAME) {
    $MONGO_DB_NAME = "myapp"
    Write-Host "  MONGO_DB_NAME not found in environment, using default: $MONGO_DB_NAME" -ForegroundColor Gray
} else {
    Write-Host "  MONGO_DB_NAME found: $MONGO_DB_NAME" -ForegroundColor Green
}

$MONGO_HOST = $env:MONGO_HOST
if (-not $MONGO_HOST) {
    $MONGO_HOST = "localhost"
    Write-Host "  MONGO_HOST not found in environment, using default: $MONGO_HOST" -ForegroundColor Gray
} else {
    Write-Host "  MONGO_HOST found: $MONGO_HOST" -ForegroundColor Green
}

$MONGO_PORT = $env:MONGO_PORT
if (-not $MONGO_PORT) {
    $MONGO_PORT = "27017"
    Write-Host "  MONGO_PORT not found in environment, using default: $MONGO_PORT" -ForegroundColor Gray
} else {
    Write-Host "  MONGO_PORT found: $MONGO_PORT" -ForegroundColor Green
}

Write-Host ""
Write-Host "Creating .env file..." -ForegroundColor Cyan

# Create .env file content
$EnvContent = @"
# MongoDB Environment Configuration
# Auto-generated by setup-env.ps1
# Created: $(Get-Date)
#
# DO NOT commit this file to version control!

MONGO_ROOT_USER=$MONGO_ROOT_USER
MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
MONGO_DB_NAME=$MONGO_DB_NAME
MONGO_HOST=$MONGO_HOST
MONGO_PORT=$MONGO_PORT
"@

Set-Content -Path $EnvFile -Value $EnvContent -Encoding UTF8

Write-Host ".env file created successfully!" -ForegroundColor Green
Write-Host "Location: $EnvFile" -ForegroundColor Green
Write-Host ""
Write-Host "Summary:" -ForegroundColor Cyan
Write-Host "  MONGO_ROOT_USER: $MONGO_ROOT_USER" -ForegroundColor White
Write-Host "  MONGO_ROOT_PASSWORD: ******* (hidden)" -ForegroundColor White
Write-Host "  MONGO_DB_NAME: $MONGO_DB_NAME" -ForegroundColor White
Write-Host "  MONGO_HOST: $MONGO_HOST" -ForegroundColor White
Write-Host "  MONGO_PORT: $MONGO_PORT" -ForegroundColor White
Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
Write-Host "  1. Review the .env file: Get-Content .\mongodb_config\.env" -ForegroundColor White
Write-Host "  2. Start MongoDB container from docker/ folder: docker-compose up -d" -ForegroundColor White
Write-Host "  3. Verify connection: docker-compose ps" -ForegroundColor White
