#!/bin/bash
# MongoDB Environment Setup Script (Bash)
#
# This script creates a .env file for MongoDB Docker setup
# It checks for system environment variables and uses them if available,
# otherwise uses the defaults from .env.example
#
# IMPORTANT: This script should be run from the mongodb/ folder or from scripts/
# It will create the .env file in the mongodb_config/ subfolder
#
# Usage (from mongodb/ folder):
#   ./scripts/setup-env.sh
#   ./scripts/setup-env.sh --force    # Overwrite existing .env file

SCRIPT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
PARENT_DIR="$( cd "$SCRIPT_DIR/.." && pwd )"
CONFIG_DIR="$PARENT_DIR/mongodb_config"
ENV_FILE="$CONFIG_DIR/.env"
ENV_EXAMPLE_FILE="$PARENT_DIR/.env.example"

echo "MongoDB Environment Setup Script"
echo "================================="
echo ""

# Parse arguments
FORCE=false
while [[ $# -gt 0 ]]; do
    case $1 in
        --force)
            FORCE=true
            shift
            ;;
        *)
            shift
            ;;
    esac
done

# Check if .env already exists
if [[ -f "$ENV_FILE" ]] && [[ "$FORCE" != true ]]; then
    echo ".env file already exists at: $ENV_FILE"
    echo "Use ./scripts/setup-env.sh --force to overwrite"
    exit 0
fi

# Get values from environment variables or use defaults
echo "Checking system environment variables..."

# MONGO_ROOT_USER
MONGO_ROOT_USER="${MONGO_ROOT_USER:-${MONGODB_USER:-admin}}"
if [[ "$MONGO_ROOT_USER" == "admin" ]] && [[ -z "$MONGO_ROOT_USER" ]]; then
    echo "  MONGO_ROOT_USER not found in environment, using default: $MONGO_ROOT_USER"
else
    echo "  MONGO_ROOT_USER found: $MONGO_ROOT_USER"
fi

# MONGO_ROOT_PASSWORD
MONGO_ROOT_PASSWORD="${MONGO_ROOT_PASSWORD:-${MONGODB_PASSWORD:-changeme}}"
if [[ "$MONGO_ROOT_PASSWORD" == "changeme" ]] && [[ -z "$MONGO_ROOT_PASSWORD" ]]; then
    echo "  MONGO_ROOT_PASSWORD not found in environment, using default: $MONGO_ROOT_PASSWORD"
    echo "  WARNING: Using default password! Change this immediately in .env for security"
else
    echo "  MONGO_ROOT_PASSWORD found in environment"
fi

# MONGO_DB_NAME
MONGO_DB_NAME="${MONGO_DB_NAME:-${MONGODB_DB_NAME:-myapp}}"
if [[ "$MONGO_DB_NAME" == "myapp" ]] && [[ -z "$MONGO_DB_NAME" ]]; then
    echo "  MONGO_DB_NAME not found in environment, using default: $MONGO_DB_NAME"
else
    echo "  MONGO_DB_NAME found: $MONGO_DB_NAME"
fi

# MONGO_HOST
MONGO_HOST="${MONGO_HOST:-localhost}"
if [[ "$MONGO_HOST" == "localhost" ]] && [[ -z "$MONGO_HOST" ]]; then
    echo "  MONGO_HOST not found in environment, using default: $MONGO_HOST"
else
    echo "  MONGO_HOST found: $MONGO_HOST"
fi

# MONGO_PORT
MONGO_PORT="${MONGO_PORT:-27017}"
if [[ "$MONGO_PORT" == "27017" ]] && [[ -z "$MONGO_PORT" ]]; then
    echo "  MONGO_PORT not found in environment, using default: $MONGO_PORT"
else
    echo "  MONGO_PORT found: $MONGO_PORT"
fi

echo ""
echo "Creating .env file..."

# Create .env file content
cat > "$ENV_FILE" << EOF
# MongoDB Environment Configuration
# Auto-generated by setup-env.sh
# Created: $(date)
#
# DO NOT commit this file to version control!

MONGO_ROOT_USER=$MONGO_ROOT_USER
MONGO_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD
MONGO_DB_NAME=$MONGO_DB_NAME
MONGO_HOST=$MONGO_HOST
MONGO_PORT=$MONGO_PORT
EOF

echo ".env file created successfully!"
echo "Location: $ENV_FILE"
echo ""
echo "Summary:"
echo "  MONGO_ROOT_USER: $MONGO_ROOT_USER"
echo "  MONGO_ROOT_PASSWORD: ******* (hidden)"
echo "  MONGO_DB_NAME: $MONGO_DB_NAME"
echo "  MONGO_HOST: $MONGO_HOST"
echo "  MONGO_PORT: $MONGO_PORT"
echo ""
echo "Next steps:"
echo "  1. Review the .env file: cat ../mongodb_config/.env"
echo "  2. Start MongoDB container from docker/ folder: docker-compose up -d"
echo "  3. Verify connection: docker-compose ps"
